### ISSUE TITLE
Breaks dashboard visibility! 

### ISSUE THREAD

**Issue by Anan5a** [prayag17/JellyFlix#1]
![IMG_20201108_111239](https://user-images.githubusercontent.com/16373480/98457623-71f9f000-21b3-11eb-8076-424dbe14b280.jpg)
After applying the stylesheet the UI becomes un viewable in the Dashboard

**Comment by prayag17** [comment]
Can you provide me the device name

**Comment by Anan5a** [comment]
It is Google chrome browser on Realme X2 

Tried Changing themes, normal user view is fine but admin dashboard become like that

**Comment by prayag17** [comment]
I don't have the device but I have emulated the device in chrome and I cannot see this happening.

**Comment by prayag17** [comment]
Is this issue coming in any other device?

**Comment by Anan5a** [comment]
@prayag17 I just checked in my computer, same result here
Dashboard after applying
![Screenshot_2020-11-10 BingeBreak by MLSBD](https://user-images.githubusercontent.com/16373480/98690359-0d978600-2397-11eb-937a-389bbf7ec0c2.png)

Normal user view after applying
![Screenshot_2020-11-10 BingeBreak by MLSBD(1)](https://user-images.githubusercontent.com/16373480/98690437-23a54680-2397-11eb-8fbb-6c27e1473571.png)


This is firefox browser. Jellyfin version ```10.6.4``` also the theme just overrides my logo :/

**Comment by prayag17** [comment]
Decrease zoom to 67%

**Comment by prayag17** [comment]
your custom logo issue is fixed

**Comment by Anan5a** [comment]
@prayag17 Thanks appreciate that.
But the theme colors on dashboard isn’t fixed,  changed zoom to 67%

Go to ```Menu>Dashboard ```  and there is the bug.  Other than that it looks fantastic 

I'm unable to fix that :( Can you give a screenshot what it supposed to look like

**Comment by prayag17** [comment]
K
