### ISSUE TITLE
Bug: Poster and Playback controls disappear on landscape mode (Android)

### ISSUE THREAD

**Issue by gerryflux** [prayag17/JellyFlix#30]
Device Name: Tablet or Phone
Type: Android

When on Landscape mode, poster and playback controls disappear - it's all black, cast and everything below it is visible just fine.
When you rotate the device back to portrait mode, everything looks okay poster and playback controls visible (slightly zoomed in) but usable.

LANDSCAPE MODE:
![Jellyfin_landscape](https://user-images.githubusercontent.com/52464120/156931235-e6097249-953a-4a1f-8e60-009f7fa3d7c7.jpg)

PORTRAIT MODE:
![Jellyfin_portrait](https://user-images.githubusercontent.com/52464120/156931238-7984093e-50d9-4857-aa31-f97a9c9d85e9.jpg)
.

**Comment by prayag17** [comment]
Are you using a tablet?

**Comment by prayag17** [comment]
This issue is fixed use version 9.1.2

**Comment by gerryflux** [comment]
> Are you using a tablet?

I use both a tablet and a phone.
The issue was on both when on landscape mode,
It is now fixed on the phone, but it is still the same issue on the tablet.

**Comment by prayag17** [comment]
I will check it out
